require "spec/rails/dsl/behaviour/render_observer"
require "spec/rails/dsl/behaviour/rails_example"
require "spec/rails/dsl/behaviour/model_example"
require "spec/rails/dsl/behaviour/functional_example"
require "spec/rails/dsl/behaviour/controller_example"
require "spec/rails/dsl/behaviour/helper_example"
require "spec/rails/dsl/behaviour/view_example"
