# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.


#NOTE - this is a bit of a hack - ideally, rails would find this file when it loads plugins
# $LOAD_PATH.unshift(File.expand_path(File.dirname(__FILE__) + "/../../rspec/lib"))
# load File.expand_path(File.dirname(__FILE__) + "/../vendor/plugins/rspec_on_rails/tasks/rspec.rake")

require(File.join(File.dirname(__FILE__), 'config', 'environment'))


require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'
