require File.dirname(__FILE__) + '/../../spec_helper'

module Spec
  module DSL
    describe BehaviourFactory, "with :foobar registered as custom type" do

      before do
        @behaviour = Class.new(ExampleGroup)
        BehaviourFactory.register(:foobar, @behaviour)
      end

      after do
        BehaviourFactory.reset!
      end

      it "should #get the default behaviour type when passed nil" do
        BehaviourFactory.get(nil).should == ExampleGroup
      end

      it "should #get custom type for :foobar" do
        BehaviourFactory.get(:foobar).should == @behaviour
      end

      it "should #get the actual type when that is passed in" do
        BehaviourFactory.get(@behaviour).should == @behaviour
      end

      it "should #get nil for unregistered non-nil values" do
        BehaviourFactory.get(:does_not_exist).should be_nil
      end

      it "should raise error for #get! with unknown key" do
        proc do
          BehaviourFactory.get!(:does_not_exist)
        end.should raise_error
      end
    end    

    describe BehaviourFactory do
      it "should create a uniquely named class" do
        behaviour = Spec::DSL::BehaviourFactory.create_behaviour("behaviour")
        behaviour.name.should =~ /Spec::DSL::ExampleGroup::Subclass_\d+/
      end

      it "should create a Spec::DSL::Example subclass by default" do
        behaviour = Spec::DSL::BehaviourFactory.create_behaviour("behaviour")
        behaviour.superclass.should == Spec::DSL::ExampleGroup
      end

      it "should create a Spec::DSL::Example when :type => :default" do
        behaviour = Spec::DSL::BehaviourFactory.create_behaviour("behaviour", :type => :default)
        behaviour.superclass.should == Spec::DSL::ExampleGroup
      end

      it "should create a Spec::DSL::Example when :behaviour_type => :default" do
        behaviour = Spec::DSL::BehaviourFactory.create_behaviour("behaviour", :behaviour_type => :default)
        behaviour.superclass.should == Spec::DSL::ExampleGroup
      end

      it "should create specified type when :type => :something_other_than_default" do
        klass = Class.new(ExampleGroup) do
          def initialize(*args, &block); end
        end
        Spec::DSL::BehaviourFactory.register(:something_other_than_default, klass)
        behaviour = Spec::DSL::BehaviourFactory.create_behaviour("behaviour", :type => :something_other_than_default)
        behaviour.superclass.should == klass
      end

      it "should create specified type when :behaviour_type => :something_other_than_default" do
        klass = Class.new(ExampleGroup) do
          def initialize(*args, &block); end
        end
        Spec::DSL::BehaviourFactory.register(:something_other_than_default, klass)
        behaviour = Spec::DSL::BehaviourFactory.create_behaviour("behaviour", :behaviour_type => :something_other_than_default)
        behaviour.superclass.should == klass
      end
      
      it "should create a type indicated by :spec_path" do
        klass = Class.new(ExampleGroup) do
          def initialize(*args, &block); end
        end
        Spec::DSL::BehaviourFactory.register(:something_other_than_default, klass)
        behaviour = Spec::DSL::BehaviourFactory.create_behaviour("behaviour", :spec_path => "./spec/something_other_than_default/some_spec.rb")
        behaviour.superclass.should == klass
      end
      
      it "should create a type indicated by :spec_path (with spec_path generated by caller on windows)" do
        klass = Class.new(ExampleGroup) do
          def initialize(*args, &block); end
        end
        Spec::DSL::BehaviourFactory.register(:something_other_than_default, klass)
        behaviour = Spec::DSL::BehaviourFactory.create_behaviour("behaviour", :spec_path => "./spec\\something_other_than_default\\some_spec.rb")
        behaviour.superclass.should == klass
      end
      
      it "should create a Spec::DSL::Example if :shared => true" do
        Spec::DSL::BehaviourFactory.create_behaviour("name", :spec_path => '/blah/spec/models/blah.rb', :behaviour_type => :controller, :shared => true) {
        }.should be_an_instance_of(Spec::DSL::SharedBehaviour)
      end

      it "should favor the :behaviour_type over the :spec_path" do
        klass = Class.new(ExampleGroup) do
          def initialize(*args, &block); end
        end
        Spec::DSL::BehaviourFactory.register(:something_other_than_default, klass)
        behaviour = Spec::DSL::BehaviourFactory.create_behaviour("name", :spec_path => '/blah/spec/models/blah.rb', :behaviour_type => :something_other_than_default)
        behaviour.superclass.should == klass
      end
      
      after(:each) do
        Spec::DSL::BehaviourFactory.reset!
      end
    end
  end
end
