require "spec/rails/example/behaviour/render_observer"
require "spec/rails/example/behaviour/rails_example"
require "spec/rails/example/behaviour/model_example"
require "spec/rails/example/behaviour/functional_example"
require "spec/rails/example/behaviour/controller_example"
require "spec/rails/example/behaviour/helper_example"
require "spec/rails/example/behaviour/view_example"
