module RCov
  # A task that can verify that the RCov coverage doesn't
  # drop below a certain threshold.
  class VerifyTask < Rake::TaskLib
    # Name of the task. Defaults to :rcov_verify
    attr_accessor :name
    
    # Path to the index.html file generated by RCov, which
    # is the file containing the total coverage.
    # Defaults to 'coverage/index.html'
    attr_accessor :index_html
    
    # Whether or not to output details
    attr_accessor :verbose
    
    # The threshold value (in percent) for coverage. If the 
    # actual coverage is below this value, the task will raise an 
    # exception
    attr_accessor :threshold
    
    def initialize(name=:rcov_verify)
      @name = name
      @index_html = 'coverage/index.html'
      @verbose = false
      yield self if block_given?
      raise "Threshold must be set" if @threshold.nil?
      define
    end
    
    def define
      desc "Verify that rcov coverage is at least #{threshold}%"
      task @name do
        total_coverage = nil
        File.open(index_html).each_line do |line|
          if line =~ /<tt>(\d+\.\d+)%<\/tt>&nbsp;<\/td>/
            total_coverage = eval($1)
            break
          end
        end
        puts "Coverage: #{total_coverage}% (threshold: #{threshold}%)" if verbose
        raise "Coverage must be at least #{threshold}% but was #{total_coverage}%" if total_coverage < threshold
      end
    end
  end
end