require 'spec/extensions/object'
require 'spec/extensions/main'
require 'spec/extensions/test/unit/autorunner'
require 'spec/extensions/test/unit/rspectestresult'
require 'spec/extensions/test/unit/ui/testrunnermediator'
