require File.dirname(__FILE__) + '/spec/spec_helper'
require 'spec/rake/spectask'

desc "Run UI Specs"
Spec::Rake::SpecTask.new('spec:ui') do |t|
  t.spec_files = FileList['spec/**/*.rb']
  t.spec_opts = [
    '--require', 'spec/spec_helper', 
    '--format', 'Spec::Ui::ScreenshotFormatter:spec_report.html',
    '--format', 'progress',
  ]
end
