# You don't need to tweak the $LOAD_PATH if you have RSpec installed as a gem
$LOAD_PATH.unshift('../../../rspec/lib')

require 'rubygems'
require 'spec/rake/spectask'

desc "Run Selenium Specs"
Spec::Rake::SpecTask.new('spec:selenium') do |t|
  t.spec_files = FileList['spec/selenium/**/*.rb']
  # This line is not necessary if you have Spec::Ui installed as a gem
  t.libs = ["../../lib"]
  t.spec_opts = [
    '--color', '--diff',
    '--require', 'rubygems,spec/ui', 
    '--format', 'Spec::Ui::ScreenshotFormatter:spec_report.html',
    '--format', 'progress'
  ]
end

# IMPORTANT: If you use the master/slave mode you really ought to
# run everything on different machines.

desc "Run Selenium Specs as Spec::Distributed slave"
Spec::Rake::SpecTask.new('spec:selenium:slave') do |t|
  t.spec_files = FileList['spec/selenium/**/*.rb']
  # This line is not necessary if you have Spec::Ui and Spec::Distributed installed as gems
  t.libs = ["../../lib", "../../../spec_distributed/lib"]
  t.spec_opts = lambda do
    url = ENV['DRB_URL']
    raise "You must pass DRB_URL=druby://localhost:8991 (for example) on the command line" if url.nil?
    [
    '--color', '--diff',
    '--require', 'rubygems,spec/ui,spec/distributed', 
    '--format', 'Spec::Ui::SlaveScreenshotFormatter:spec_report.html',
    '--format', 'progress',
    '--runner', "Spec::Distributed::SlaveRunner:#{url}"
    ]
  end
end

desc "Run Selenium Specs as Spec::Distributed master"
Spec::Rake::SpecTask.new('spec:selenium:master') do |t|
  t.spec_files = FileList['spec/selenium/**/*.rb']
  # This line is not necessary if you have Spec::Ui and Spec::Distributed installed as gems
  t.libs = ["../../lib", "../../../spec_distributed/lib"]
  t.spec_opts = lambda do
    urls = ENV['DRB_URLS']
    raise "You must pass DRB_URLS=druby://localhost:8991,druby://localhost:8991 (for example) on the command line" if urls.nil?
    [
    '--color', '--diff',
    '--require', 'rubygems,spec/ui,spec/distributed', 
    '--format', 'Spec::Ui::MasterScreenshotFormatter:spec_report.html',
    '--format', 'progress',
    '--runner', "Spec::Distributed::MasterRunner:#{urls}"
    ]
  end
end
